In [1]:
import json
import time
import re
import urllib
from datetime import date
import polars as pl
import numpy as np
import textdistance as td
import requests
from bs4 import BeautifulSoup
import nltk
from nltk.stem.cistem import Cistem
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/tobias/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
schema={
    'id': pl.Utf8,
    'abstract': pl.Utf8,
    'beratungsstand': pl.Utf8,
    'vorgangstyp': pl.Utf8,
    'gesta': pl.Utf8,
    'archiv': pl.Utf8,
    'sachgebiet': pl.List(pl.Utf8),
    'typ': pl.Utf8,
    'wahlperiode': pl.UInt64,
    'zustimmungsbeduerftigkeit': pl.List(pl.Utf8),
    'initiative': pl.List(pl.Utf8),
    'deskriptor': pl.List(pl.Struct([
        pl.Field('fundstelle', pl.Boolean),
        pl.Field('name', pl.Utf8),
        pl.Field('typ', pl.Utf8),
    ])),
    'aktualisiert': pl.Utf8,
    'titel': pl.Utf8,
    'datum': pl.Utf8,
    'verkuendung': pl.List(pl.Struct([
        pl.Field('verkuendungsdatum', pl.Utf8)
    ]))
}
df_vorgang = pl.DataFrame(json.load(open('vorgang.json', encoding='utf-8')), schema=schema)
df_gesetze = df_vorgang.filter(pl.col('vorgangstyp') == 'Gesetzgebung')
pl.Config(fmt_str_lengths=100)
df_gesetze['beratungsstand'].unique()

shape: (17,)
Series: 'beratungsstand' [str]
[
	"Verabschiedet"
	"Bundesrat hat Zustimmung versagt"
	"Verkündet"
	"Einbringung abgelehnt"
	"Einbringung beschlossen"
	…
	"Dem Bundestag zugeleitet - Noch nicht beraten"
	"Den Ausschüssen zugewiesen"
	"Überwiesen"
	"Beschlussempfehlung liegt vor"
	"Für erledigt erklärt"
]

In [3]:
df_vorgangspos = pl.read_json('vorgangsposition.json', infer_schema_length=20000)
df_vorgangspos = df_vorgangspos.with_columns(
   pl.col("datum").str.to_date(format="%Y-%m-%d")
)
df_vorgangspos_gesetzgebung = df_vorgangspos.filter((pl.col('vorgangstyp') == 'Gesetzgebung') & (pl.col('typ') == 'Vorgangsposition'))
df_vorgang_duration = df_vorgangspos_gesetzgebung.group_by(['vorgang_id']).agg([
    pl.col('datum').min().alias('vorgang_start'), 
])

In [4]:
df_gesetze.head()

shape: (5, 16)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ abstract   ┆ beratungss ┆ vorgangst ┆ … ┆ aktualisi ┆ titel     ┆ datum     ┆ verkuendu │
│ ---    ┆ ---        ┆ tand       ┆ yp        ┆   ┆ ert       ┆ ---       ┆ ---       ┆ ng        │
│ str    ┆ str        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---       │
│        ┆            ┆ str        ┆ str       ┆   ┆ str       ┆           ┆           ┆ list[stru │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ ct[1]]    │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 336482 ┆ null       ┆ Überwiesen ┆ Gesetzgeb ┆ … ┆ 2026-06-2 ┆ Gesetz    ┆ 2026-06-2 ┆ null      │
│        ┆            ┆            ┆ ung       ┆   ┆ 6T11:02:4 ┆ zum       ┆ 5         ┆           │
│        ┆            ┆            ┆           ┆   ┆ 8+02:00   ┆ Schließen ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ einer Ger ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ echtigkei ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ tslücke   ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ bei der   ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ Besteueru ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ ng von    ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ Immobilie ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ nveräußer ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ ungen     ┆           ┆           │
│ 335824 ┆ Maßnahmen  ┆ Abgelehnt  ┆ Gesetzgeb ┆ … ┆ 2026-06-2 ┆ Gesetz    ┆ 2026-06-2 ┆ null      │
│        ┆ zur        ┆            ┆ ung       ┆   ┆ 6T11:18:0 ┆ zur       ┆ 5         ┆           │
│        ┆ Senkung    ┆            ┆           ┆   ┆ 6+02:00   ┆ Aufhebung ┆           ┆           │
│        ┆ der Energi ┆            ┆           ┆   ┆           ┆ des Treib ┆           ┆           │
│        ┆ ekosten    ┆            ┆           ┆   ┆           ┆ hausgas-E ┆           ┆           │
│        ┆ für Untern ┆            ┆           ┆   ┆           ┆ missionsh ┆           ┆           │
│        ┆ ehmen und  ┆            ┆           ┆   ┆           ┆ andelsges ┆           ┆           │
│        ┆ Privathaus ┆            ┆           ┆   ┆           ┆ etzes und ┆           ┆           │
│        ┆ halte und  ┆            ┆           ┆   ┆           ┆ des Brenn ┆           ┆           │
│        ┆ zur        ┆            ┆           ┆   ┆           ┆ stoffemis ┆           ┆           │
│        ┆ Stärkung   ┆            ┆           ┆   ┆           ┆ sionshand ┆           ┆           │
│        ┆ der Wet…   ┆            ┆           ┆   ┆           ┆ elsges…   ┆           ┆           │
│ 335821 ┆ Senkung    ┆ Abgelehnt  ┆ Gesetzgeb ┆ … ┆ 2026-06-2 ┆ Gesetz    ┆ 2026-06-2 ┆ null      │
│        ┆ der Heiz-  ┆            ┆ ung       ┆   ┆ 6T11:15:1 ┆ zur dauer ┆ 5         ┆           │
│        ┆ und Produk ┆            ┆           ┆   ┆ 8+02:00   ┆ haften    ┆           ┆           │
│        ┆ tionskoste ┆            ┆           ┆   ┆           ┆ Ermäßigun ┆           ┆           │
│        ┆ n durch    ┆            ┆           ┆   ┆           ┆ g der Ums ┆           ┆           │
│        ┆ einen      ┆            ┆           ┆   ┆           ┆ atzsteuer ┆           ┆           │
│        ┆ dauerhaft  ┆            ┆           ┆   ┆           ┆ auf Gas   ┆           ┆           │
│        ┆ ermäßigten ┆            ┆           ┆   ┆           ┆ und Wärme ┆           ┆           │
│        ┆ Umsatzsteu ┆            ┆           ┆   ┆           ┆ (Gas- und ┆           ┆           │
│        ┆ ersatz von ┆            ┆           ┆   ┆           ┆ Wärme-Ums ┆           ┆           │
│        ┆ 7 Proz…    ┆            ┆           ┆   ┆           ┆ atzsteuer ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ sen…      ┆           ┆           │
│ 335818 ┆ Entlastung ┆ Abgelehnt  ┆ Gesetzgeb ┆ … ┆ 2026-06-2 ┆ Gesetz    ┆ 2026-06-2 ┆ null      │
│        ┆ von        ┆            ┆ ung       ┆   ┆ 6T11:14:1 ┆ zur fläch ┆ 5         ┆           │
│        ┆ Wirtschaft ┆            ┆           ┆   ┆ 7+02:00   ┆ endeckend ┆           ┆           │
│        ┆ und Verbra ┆            ┆           ┆   ┆           ┆ en        ┆           ┆           │
│        ┆ uchern     ┆            ┆           ┆   ┆           ┆ Absenkung ┆           ┆           │
│        ┆ durch      ┆            ┆           ┆   ┆           ┆ der       ┆           ┆           │
│        ┆ Umstellung ┆            ┆           ┆   ┆           ┆ Energie-  ┆           ┆           │
│        ┆ des        ┆            ┆           ┆   ┆           ┆ und Strom ┆           ┆           │
│        ┆ bisherigen ┆            ┆           ┆   ┆           ┆ steuersät ┆           ┆           │
│        ┆ Systems    ┆            ┆           ┆   ┆           ┆ ze        ┆           ┆           │
│        ┆ hoher Rege ┆            ┆           ┆   ┆           ┆ (Energie- ┆           ┆           │
│        ┆ lsteuer…   ┆            ┆           ┆   ┆           ┆ und Strom ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ steuersen ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ …         ┆           ┆           │
│ 335478 ┆ Vereinfach ┆ Überwiesen ┆ Gesetzgeb ┆ … ┆ 2026-06-2 ┆ Gesetz    ┆ 2026-06-2 ┆ null      │
│        ┆ ung und    ┆            ┆ ung       ┆   ┆ 6T11:00:5 ┆ zur Moder ┆ 5         ┆           │
│        ┆ Beschleuni ┆            ┆           ┆   ┆ 5+02:00   ┆ nisierung ┆           ┆           │
│        ┆ gung der   ┆            ┆           ┆   ┆           ┆ des Städt ┆           ┆           │
│        ┆ Bauleitpla ┆            ┆           ┆   ┆           ┆ ebau- und ┆           ┆           │
│        ┆ nung und   ┆            ┆           ┆   ┆           ┆ Raumordnu ┆           ┆           │
│        ┆ Raumordnun ┆            ┆           ┆   ┆           ┆ ngsrechts ┆           ┆           │
│        ┆ g: vollstä ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ ndige Digi ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ talisierun ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ g de…      ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
df_gesetze = df_gesetze.join(df_vorgang_duration.select(['vorgang_id', 'vorgang_start']), left_on='id', right_on='vorgang_id', how='left')

In [6]:
#df_vorgang_docs = df_vorgangspos.filter(pl.col('dokumentart') == 'Drucksache').group_by('vorgang_id').agg(pl.col('fundstelle').struct.field("dokumentnummer").explode())
#df_gesetze = df_gesetze.join(df_vorgang_docs.select(['vorgang_id', 'dokumentnummer']), left_on='id', right_on='vorgang_id', how='left')

In [7]:
today = date.today()
df_gesetze = df_gesetze.with_columns(
    pl.when(pl.col('beratungsstand') == 'Verkündet').then(
        pl.col('verkuendung').list.eval(pl.col('').struct.field('verkuendungsdatum').str.to_date(format="%Y-%m-%d")).list.min()
    ).when(pl.col('beratungsstand') == 'Abgelehnt').then(
        pl.col('datum').str.to_date(format="%Y-%m-%d")
    ).otherwise(today).alias('vorgang_end')
)
df_gesetze = df_gesetze.with_columns((pl.col('vorgang_end') - pl.col('vorgang_start')).dt.total_days().alias('vorgangsdauer'))

In [8]:
reg_frag = ['Fraktion der CDU/CSU', 'Fraktion der SPD']

def fix_initiative(x):
    return pl.when(x.list.set_intersection(reg_frag).len == len(reg_frag)).then(
        x.list.set_difference(reg_frag)
    ).otherwise(x)

df_gesetze = df_gesetze.with_columns(pl.when(pl.col('initiative').list.set_intersection(reg_frag).list.len() == len(reg_frag)).then(
        pl.col('initiative').list.set_difference(reg_frag).list.concat(pl.Series(['Bundesregierung']))
    ).otherwise(pl.col('initiative')).alias('initiative'))

In [9]:
df_gesetze = df_gesetze.with_columns(pl.col('deskriptor').list.eval(pl.element().struct.field('name')).alias('keywords'))

In [10]:
df_gesetze.select(pl.col("*").exclude("abstract", "vorgangstyp", "gesta", "archiv", "typ", "deskriptor")).write_json('gesetze.json')

In [11]:
df_gesetze_public = df_gesetze.filter(pl.col('beratungsstand') == 'Verkündet')
bins = [7, 14, 30, 60, 120, 240, 365]
duration_bin = np.digitize(df_gesetze_public.select('vorgangsdauer').to_series(), bins, right=True)
df_gesetze_public.select('vorgangsdauer').to_series().hist(bins)

shape: (6, 3)
┌────────────┬────────────────┬───────┐
│ breakpoint ┆ category       ┆ count │
│ ---        ┆ ---            ┆ ---   │
│ f64        ┆ cat            ┆ u32   │
╞════════════╪════════════════╪═══════╡
│ 14.0       ┆ [7.0, 14.0]    ┆ 1     │
│ 30.0       ┆ (14.0, 30.0]   ┆ 1     │
│ 60.0       ┆ (30.0, 60.0]   ┆ 13    │
│ 120.0      ┆ (60.0, 120.0]  ┆ 52    │
│ 240.0      ┆ (120.0, 240.0] ┆ 73    │
│ 365.0      ┆ (240.0, 365.0] ┆ 3     │
└────────────┴────────────────┴───────┘

In [12]:
df_gesetze_public_bins = df_gesetze_public.with_columns(pl.from_numpy(duration_bin, schema=['duration_bin']))
df_gesetze_public_bins.filter(pl.col('duration_bin') == pl.col('duration_bin').min())

shape: (1, 21)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ abstract   ┆ beratungss ┆ vorgangst ┆ … ┆ vorgang_e ┆ vorgangsd ┆ keywords  ┆ duration_ │
│ ---    ┆ ---        ┆ tand       ┆ yp        ┆   ┆ nd        ┆ auer      ┆ ---       ┆ bin       │
│ str    ┆ str        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ list[str] ┆ ---       │
│        ┆            ┆ str        ┆ str       ┆   ┆ date      ┆ i64       ┆           ┆ i64       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 332608 ┆ Maßnahmen  ┆ Verkündet  ┆ Gesetzgeb ┆ … ┆ 2026-03-3 ┆ 14        ┆ ["Benzin" ┆ 1         │
│        ┆ zur        ┆            ┆ ung       ┆   ┆ 1         ┆           ┆ , "Beweis ┆           │
│        ┆ Begegnung  ┆            ┆           ┆   ┆           ┆           ┆ last", …  ┆           │
│        ┆ der Preisv ┆            ┆           ┆   ┆           ┆           ┆ "Wettbewe ┆           │
│        ┆ olatilität ┆            ┆           ┆   ┆           ┆           ┆ rb"]      ┆           │
│        ┆ an öffentl ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ ichen Tank ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ stellen    ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ und zur    ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ Erhöhung   ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ der        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ Preisv…    ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
df_gesetze_public_bins.filter(pl.col('duration_bin') == pl.col('duration_bin').max())

shape: (3, 21)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ abstract   ┆ beratungss ┆ vorgangst ┆ … ┆ vorgang_e ┆ vorgangsd ┆ keywords  ┆ duration_ │
│ ---    ┆ ---        ┆ tand       ┆ yp        ┆   ┆ nd        ┆ auer      ┆ ---       ┆ bin       │
│ str    ┆ str        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ list[str] ┆ ---       │
│        ┆            ┆ str        ┆ str       ┆   ┆ date      ┆ i64       ┆           ┆ i64       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 325529 ┆ Umsetzung  ┆ Verkündet  ┆ Gesetzgeb ┆ … ┆ 2026-05-1 ┆ 255       ┆ ["Absatzf ┆ 6         │
│        ┆ der EU-Ver ┆            ┆ ung       ┆   ┆ 8         ┆           ┆ inanzieru ┆           │
│        ┆ braucherkr ┆            ┆           ┆   ┆           ┆           ┆ ngsaufsic ┆           │
│        ┆ editrichtl ┆            ┆           ┆   ┆           ┆           ┆ htsgesetz ┆           │
│        ┆ inie: Neur ┆            ┆           ┆   ┆           ┆           ┆ ", "Bunde ┆           │
│        ┆ egelungen  ┆            ┆           ┆   ┆           ┆           ┆ sdatensch ┆           │
│        ┆ insbes.    ┆            ┆           ┆   ┆           ┆           ┆ utzgesetz ┆           │
│        ┆ betr.      ┆            ┆           ┆   ┆           ┆           ┆ ", …      ┆           │
│        ┆ Ausweitung ┆            ┆           ┆   ┆           ┆           ┆ "Zins"]   ┆           │
│        ┆ des Anwend ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ ungsb…     ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ 324928 ┆ Umfangreic ┆ Verkündet  ┆ Gesetzgeb ┆ … ┆ 2026-05-1 ┆ 276       ┆ ["Arbeitn ┆ 6         │
│        ┆ he         ┆            ┆ ung       ┆   ┆ 8         ┆           ┆ ehmer-Ent ┆           │
│        ┆ Maßnahmen  ┆            ┆           ┆   ┆           ┆           ┆ sendegese ┆           │
│        ┆ zur Verein ┆            ┆           ┆   ┆           ┆           ┆ tz", "Arb ┆           │
│        ┆ fachung    ┆            ┆           ┆   ┆           ┆           ┆ eitnehmer ┆           │
│        ┆ des Vergab ┆            ┆           ┆   ┆           ┆           ┆ haftung", ┆           │
│        ┆ erechts,   ┆            ┆           ┆   ┆           ┆           ┆ … "Öffent ┆           │
│        ┆ zum Bürokr ┆            ┆           ┆   ┆           ┆           ┆ licher    ┆           │
│        ┆ atieabbau  ┆            ┆           ┆   ┆           ┆           ┆ Auftrag"] ┆           │
│        ┆ sowie zur  ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ Digitalisi ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ 324929 ┆ Sicherung  ┆ Verkündet  ┆ Gesetzgeb ┆ … ┆ 2026-04-3 ┆ 258       ┆ ["Arbeitg ┆ 6         │
│        ┆ der Funkti ┆            ┆ ung       ┆   ┆ 0         ┆           ┆ eber",    ┆           │
│        ┆ onsfähigke ┆            ┆           ┆   ┆           ┆           ┆ "Arbeitne ┆           │
│        ┆ it der Tar ┆            ┆           ┆   ┆           ┆           ┆ hmer", …  ┆           │
│        ┆ ifautonomi ┆            ┆           ┆   ┆           ┆           ┆ "Öffentli ┆           │
│        ┆ e, Stabili ┆            ┆           ┆   ┆           ┆           ┆ cher      ┆           │
│        ┆ sierung    ┆            ┆           ┆   ┆           ┆           ┆ Auftrag"] ┆           │
│        ┆ des Tarifv ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ ertragssys ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ tems und   ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ Bes…       ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
def map_gesetze(tokens):
    overlap = df_gesetze.with_columns(pl.col('titel.stem').map_elements(lambda x: td.lcsstr.normalized_similarity(tokens, x), return_dtype=pl.Float64).alias('similarity')).select(['titel', 'titel.stem', 'id', 'similarity'])
    overlap_ = overlap.sort('similarity', descending=True)
    overlap = overlap_.filter(pl.col('similarity') > 0.5)
    if overlap.shape[0] == 0:
        print(f'Warning: Count not find any Gesetze with similarity > 0.5: {tokens}')
        print(overlap_.head())
        return None
    if overlap.shape[0] > 1:
        if overlap.row(1, named=True)['similarity'] * 2 > overlap.row(0, named=True)['similarity'] and overlap.row(0, named=True)['similarity'] != 1:
            print(f'Error: could not map gesetz: {tokens}')
            print(overlap.head())
            return None
    #print(tokens)
    #print(overlap.head())
    return overlap.row(0, named=True)

bad_words = [
    'beratung',
    'gebrach',
    'entwurf',
    'eine'
]
stopwords_german = stopwords.words('german')
def rm_stop_words(txt):
    words = txt.split()
    words = list(filter(lambda x: x not in stopwords_german, words))
    return ' '.join(words)
    
def pre_process(txt):
    txt = txt.split('eingebrach', 1)[1]
    txt = ' '.join(txt.split())
    txt = re.sub(r'[a-z]\)\(', '', txt)
    txt = re.sub(r'des von (der|den) .*(fraktio|bundesregierung)', '', txt)
    txt = re.sub(r'^–', '', txt)
    for word in bad_words:
        txt = txt.replace(word, '', 1)
    return rm_stop_words(txt)

stemmer = Cistem()
def stem(txt):
    words = []
    for word in txt.split():
        words.append(stemmer.segment(word)[0])
    return ' '.join(words)

def parse_top_details(details):
    top_l = []
    for top in str(details).split('<br/><br/>'):
        top = BeautifulSoup(top, 'lxml')
        vorgang_id = None
        for a in top.find_all('a'):
            drucksache = df_vorgangspos.filter((pl.col('dokumentart') == 'Drucksache') & (pl.col('fundstelle').struct.field("drucksachetyp") == 'Gesetzentwurf') & (pl.col('fundstelle').struct.field("pdf_url") == a['href']))
            if drucksache.shape[0] == 0:
                continue
            if drucksache.shape[0] == 1:
                vorgang_id_new = drucksache.row(0, named=True)['vorgang_id']
                if vorgang_id and vorgang_id != vorgang_id_new:
                    gesetz = df_gesetze.filter(pl.col('id') == vorgang_id).row(0, named=True)
                    print('* ' + gesetz['titel'])
                    top_l.append(gesetz)
                    # warning: more then one gesetz discussed in one TOP
                vorgang_id = vorgang_id_new
            if drucksache.shape[0] > 1:
                print(drucksache)
                raise RuntimeError('Found multiple vorgang ids for document')
        if vorgang_id:
            gesetz = df_gesetze.filter(pl.col('id') == vorgang_id).row(0, named=True)
            print('* ' + gesetz['titel'])
            top_l.append(gesetz)
        else:
            txt_ = top.get_text(' ')
            for txt in txt_.split('Drucksache'):
                if 'gesetz' in txt.lower() and 'entwurf' in txt.lower():
                    txt = stem(txt)
                    txt = pre_process(txt)
                    gesetz = map_gesetze(txt)
                    if gesetz is not None:
                        print('* ' + gesetz['titel'])
                        top_l.append(gesetz)
    return top_l

def map_top_gesetze(soup):
    tagesordnung = {}
    for conf in soup.find_all('div', {'class': 'bt-conference-title'}):
        sitzung = conf.text.strip()
        print(sitzung)
        top_l = []
        for thema in conf.parent.parent.find_all('td', {'data-th': 'Thema'}):
            if thema.p:
                top_l += parse_top_details(thema.p)
        print()
        tagesordnung[sitzung] = top_l
    return tagesordnung

def get_tagesordnung_gesetze_html(kw):
    res = requests.get('https://www.bundestag.de/apps/plenar/plenar/conferenceweekDetail.form', {'year': 2025, 'week': kw, 'limit': 10})
    time.sleep(0.3)
    soup = BeautifulSoup(res.text, 'lxml')
    return map_top_gesetze(soup)

def get_tagesordnung_gesetze_json(kw=None, year=None):
    args = None
    if kw and year:
        args = {'year': year, 'week': kw}
    res = requests.get('https://www.bundestag.de/apps/plenar/plenar/conferenceWeekJSON', args)
    time.sleep(0.3)
    return res.json()

def get_tagesordnung_gesetze():
    tagesordnung = {}
    current_week = get_tagesordnung_gesetze_json()
    conferences = current_week["conferences"]
    if "previous" in current_week:
        prev_week = get_tagesordnung_gesetze_json(current_week["previous"]["week"], current_week["previous"]["year"])
        conferences += prev_week["conferences"]
    if "next" in current_week:
        next_week = get_tagesordnung_gesetze_json(current_week["next"]["week"], current_week["next"]["year"])
        conferences += next_week["conferences"]
    conferences = sorted(conferences, key=lambda x: x["conferenceNumber"])
    for day in conferences:
        sitzung = f'{day["conferenceDate"]["date"]} ({day["conferenceNumber"]}. Sitzung)'
        print(sitzung)
        top_l = []
        for top in day["rows"]:
            topic = top["topic"]
            title = topic["title"]
            detail = None
            link = None
            if "detail" in topic:
                detail = topic["detail"]
            if "link" in topic:
                link = topic["link"]
            top_l += parse_top_details(detail)
        tagesordnung[sitzung] = top_l
        print()
    return tagesordnung

In [15]:
df_gesetze = df_gesetze.with_columns(pl.col('titel').map_elements(stem, return_dtype=pl.self_dtype()).map_elements(rm_stop_words, return_dtype=pl.self_dtype()).alias('titel.stem'))

In [16]:
#df_vorgangspos.filter((pl.col('dokumentart') == 'Drucksache')).select(pl.col('fundstelle').struct.field("pdf_url"))
#df_vorgangspos.filter(pl.col('fundstelle').struct.field("pdf_url").eq('https://dserver.bundestag.de/btd/20/106/2010664.pdf'))

In [17]:
top = get_tagesordnung_gesetze()

10. Juni 2026 (82. Sitzung)
* ... Gesetz zur Änderung der Strafprozessordnung - Zeugnisverweigerungsrecht in der Sozialen Arbeit und ehrenamtlichen Rechtsberatung

11. Juni 2026 (83. Sitzung)
* Gesetz zur Änderung des Gebäudeenergiegesetzes, zur Änderung des Gebäude-Elektromobilitätsinfrastruktur-Gesetzes und zur Änderung weiterer Vorschriften im Wärmebereich
* Gesetz zur flächendeckenden Absenkung der Energie- und Stromsteuersätze (Energie- und Stromsteuersenkungsgesetz)
* Gesetz zur dauerhaften Ermäßigung der Umsatzsteuer auf Gas und Wärme (Gas- und Wärme-Umsatzsteuersenkungsgesetz)
* Gesetz zur Aufhebung des Treibhausgas-Emissionshandelsgesetzes und des Brennstoffemissionshandelsgesetzes (CO2-Preis-Abschaffungsgesetz)
* Gesetz zur Ermöglichung der digitalen Fluggastabfertigung
* Gesetz zu dem Abkommen vom 29. Juli 2025 zwischen der Regierung der Bundesrepublik Deutschland und der Regierung der Französischen Republik über die Deutsch-Französischen Gymnasien und das Deutsch-Französische Abitur
* Zweites Gesetz zur Änderung des Allgemeinen Gleichbehandlungsgesetzes
* Gesetz zur Abschaffung des § 188 des Strafgesetzbuches (Meinungsfreiheits- und Demokratiestärkungsgesetz)
* Gesetz zur Sicherung der Versorgungssicherheit Strom und zur Bereitstellung neuer Kapazitäten und zur Änderung der Besonderen Gebührenverordnung BNetzA
* ... Gesetz zur Änderung des Erneuerbare-Energien-Gesetzes zur Beschleunigung des Ausbaus der Windenergie an Land
* Gesetz zur Durchführung der Verordnung (EU) 2024/1689 des Europäischen Parlaments und des Rates vom 13. Juni 2024 zur Festlegung harmonisierter Vorschriften für künstliche Intelligenz und zur Änderung der Verordnungen (EG) Nr. 300/2008, (EU) Nr. 167/2013, (EU) Nr. 168/2013, (EU) 2018/858, (EU) 2018/1139 und (EU) 2019/2144 sowie der Richtlinien 2014/90/EU, (EU) 2016/797 und (EU) 2020/1828 (Gesetz zur Durchführung der Verordnung über künstliche Intelligenz)
* Gesetz zum Bürokratierückbau in der Gewerbeordnung und dem Energieverbrauchskennzeichnungsgesetz sowie anderer Rechtsvorschriften zur Aufhebung von Berichtspflichten
* Gesetz zur Anpassung des Verpackungsrechts und anderer Rechtsbereiche an die Verordnung (EU) 2025/40
* Neuntes Gesetz zur Änderung von Vorschriften im Steuerberatungsrecht sowie im Steuerrecht
* Gesetz zur Abweichung von dem Anpassungsverfahren gemäß § 11 Absatz 4 des Abgeordnetengesetzes für das Jahr 2026 (Anpassungsverfahrensabweichungsgesetz 2026)
* Gesetz zur Durchführung der Verordnung (EU) 2024/2847 über horizontale Cybersicherheitsanforderungen für Produkte mit digitalen Elementen (Cyberresilienz-Verordnung)
* Zweites Gesetz zur Änderung des Bundesbedarfsplangesetzes
* Gesetz zur Haftung bei Unfällen mit Elektrokleinstfahrzeugen im Straßenverkehr
* Gesetz zur Modernisierung des Designrechts
* Gesetz zur Änderung des Strafrechts - Umsetzung der Richtlinie (EU) 2024/1203 über den strafrechtlichen Schutz der Umwelt sowie zur Änderung der Zustellungspauschalen und Gebühren im Gesetz über Ordnungswidrigkeiten und in den Justizkostengesetzen
* Zweites Gesetz zur Änderung des Düngegesetzes

12. Juni 2026 (84. Sitzung)
* Gesetz zur Stabilisierung der Beitragssätze in der gesetzlichen Krankenversicherung (GKV-Beitragssatzstabilisierungsgesetz)
* Gesetz zur besseren Verhinderung missbräuchlicher Anerkennungen der Vaterschaft und zur Änderung weiterer Vorschriften
* Gesetz zur Reform der missbräuchlichen Anerkennung von Vaterschaften
* Gesetz zur Stärkung der Rechte von Verletzten insbesondere schwerer Gewalt- und Sexualstraftaten auf psychosoziale Prozessbegleitung

24. Juni 2026 (85. Sitzung)
* Gesetz zur Einführung einer IP-Adressspeicherung und Weiterentwicklung der Befugnisse zur Datenerhebung im Strafverfahren

25. Juni 2026 (86. Sitzung)
* Gesetz zur Stärkung der Cybersicherheit
* Gesetz zur Modernisierung des Städtebau- und Raumordnungsrechts
* Gesetz zum Schließen einer Gerechtigkeitslücke bei der Besteuerung von Immobilienveräußerungen
* Zweites Gesetz zur Änderung des Straßenverkehrsunfallstatistikgesetzes
* Gesetz zu der Mehrseitigen Vereinbarung vom 15. Januar 2025 zwischen den zuständigen Behörden über den Austausch von GloBE-Informationen
* Drittes Gesetz zur Änderung des Seelotsgesetzes
* Gesetz zur Umsetzung der Richtlinien (EU) 2025/1 und (EU) 2025/2 zur Festlegung eines Rahmens für die Sanierung und Abwicklung von Versicherungsunternehmen sowie zur Änderung des Aufsichtsrahmens für Versicherungsunternehmen (Versicherungs-Sanierungs-Abwicklungs-und-Aufsichtsänderungs-Gesetz - VSAAG)
* Gesetz zur Modernisierung des Verpflichtungsgesetzes und zur Änderung des Europäische-Staatsanwaltschaft-Gesetzes
* Erstes Unternehmensstatistikreformgesetz
* Gesetz zur flächendeckenden Absenkung der Energie- und Stromsteuersätze (Energie- und Stromsteuersenkungsgesetz)
* Gesetz zur dauerhaften Ermäßigung der Umsatzsteuer auf Gas und Wärme (Gas- und Wärme-Umsatzsteuersenkungsgesetz)
* Gesetz zur Aufhebung des Treibhausgas-Emissionshandelsgesetzes und des Brennstoffemissionshandelsgesetzes (CO2-Preis-Abschaffungsgesetz)
* Gesetz zur Verbesserung der Rahmenbedingungen für die Erprobung von Innovationen in Reallaboren und zur Förderung des regulatorischen Lernens
* Gesetz zur Verbesserung der Rahmenbedingungen für die Erprobung von Innovationen in Reallaboren und zur Förderung des regulatorischen Lernens
* Gesetz zur Umsetzung der Richtlinie (EU) 2024/1799 zur Förderung der Reparatur von Waren
* Gesetz zur Änderung des Umwelt-Rechtsbehelfsgesetzes und weiterer umweltrechtlicher Vorschriften
* Gesetz zum Entzug des Klagerechts für staatsfinanzierte Nichtregierungsorganisationen
* Gesetz zur Änderung des Wärmeplanungsgesetzes
* Gesetz zur Entlastung der Länder und ihrer Kommunen (Länder- und Kommunalentlastungsgesetz - LKEG)

26. Juni 2026 (87. Sitzung)
* Infrastruktur-Zukunftsgesetz
* Gesetz zur Änderung des Grundgesetzes (Artikel 19)
* Gesetz zur Ermöglichung der digitalen Fluggastabfertigung
* Gesetz zur Stärkung der strafrechtlichen Verfolgung des Menschenhandels und der sexuellen Ausbeutung sowie zur Umsetzung der Richtlinie (EU) 2024/1712

8. Juli 2026 (88. Sitzung)
* Gesetz zur Änderung der Strafprozessordnung - digitale Ermittlungsmaßnahmen
* Gesetz zur Stärkung digitaler Ermittlungsbefugnisse in der Polizeiarbeit
* Gesetz zur Stärkung digitaler Ermittlungsbefugnisse zur Abwehr von Gefahren des internationalen Terrorismus

9. Juli 2026 (89. Sitzung)
* Gesetz zur Sicherung der Versorgungssicherheit Strom und zur Bereitstellung neuer Kapazitäten und zur Änderung der Besonderen Gebührenverordnung BNetzA
Warning: Count not find any Gesetze with similarity > 0.5: gesetz regelung schienenpersonenfernverkehrsangebot
shape: (5, 4)
┌──────────────────────────────────────┬─────────────────────────────────────┬────────┬────────────┐
│ titel                                ┆ titel.stem                          ┆ id     ┆ similarity │
│ ---                                  ┆ ---                                 ┆ ---    ┆ ---        │
│ str                                  ┆ str                                 ┆ str    ┆ f64        │
╞══════════════════════════════════════╪═════════════════════════════════════╪════════╪════════════╡
│ Gesetz zur Änderung des              ┆ gesetz änderung                     ┆ 333696 ┆ 0.176471   │
│ Straßenverkehrsgesetzes (Tempolimit) ┆ straßenverkehrsgesetz (tempolimit)  ┆        ┆            │
│ Gesetz zur Reform der                ┆ gesetz reform notfallversorgung     ┆ 334560 ┆ 0.176471   │
│ Notfallversorgung                    ┆                                     ┆        ┆            │
│ Gesetz zur Änderung                  ┆ gesetz änderung kindergeldrechtlich ┆ 335058 ┆ 0.176471   │
│ kindergeldrechtlicher Regelungen     ┆ regelung                            ┆        ┆            │
│ Gesetz zur Reform der                ┆ gesetz reform missbräuchlich        ┆ 331625 ┆ 0.173077   │
│ missbräuchlichen Anerkennung von     ┆ anerkennung vaterschaft             ┆        ┆            │
│ Vaterschaften                        ┆                                     ┆        ┆            │
│ Zweites Gesetz zur Änderung des      ┆ zweit gesetz änderung               ┆ 333599 ┆ 0.156863   │
│ Luftverkehrsteuergesetzes            ┆ luftverkehrsteuergesetz             ┆        ┆            │
└──────────────────────────────────────┴─────────────────────────────────────┴────────┴────────────┘
* Gesetz zur Änderung des Straßenverkehrsgesetzes (Tempolimit)
* Gesetz zur Einführung eines antragslosen Kindergeldes
* Gesetz zur Änderung kindergeldrechtlicher Regelungen
* Gesetz zur Änderung des Versorgungsausgleichsrechts
* Gesetz zu der Mehrseitigen Vereinbarung vom 15. Januar 2025 zwischen den zuständigen Behörden über den Austausch von GloBE-Informationen
* Gesetz zur Änderung des Preisangabenrechts zur Sanktionierung von Verstößen gegen nationale und europäische Regelungen über Preisangaben
* Zweites Gesetz zur Änderung des Straßenverkehrsunfallstatistikgesetzes
* Gesetz zur Änderung des Rechts der Wohn- und Geschäftsraummiete
* Drittes Gesetz zur Änderung des Vereinsgesetzes
* Gesetz zur Entlastung der Länder und ihrer Kommunen (Länder- und Kommunalentlastungsgesetz - LKEG)
* Gesetz zur Haftung bei Unfällen mit Elektrokleinstfahrzeugen im Straßenverkehr
* Gesetz zur Modernisierung des Verpflichtungsgesetzes und zur Änderung des Europäische-Staatsanwaltschaft-Gesetzes
* Fünftes Gesetz zur Änderung des Tierschutzgesetzes

10. Juli 2026 (90. Sitzung)
* Gesetz zur Stabilisierung der Beitragssätze in der gesetzlichen Krankenversicherung (GKV-Beitragssatzstabilisierungsgesetz)
* Gesetz zur Abweichung von dem Anpassungsverfahren gemäß § 11 Absatz 4 des Abgeordnetengesetzes für das Jahr 2026 (Anpassungsverfahrensabweichungsgesetz 2026)
* Gesetz zur Streichung der automatischen Anpassung der Abgeordnetenentschädigung
* Gesetz zur Aussetzung des Anpassungsverfahrens gemäß § 11 Absatz 4 des Abgeordnetengesetzes für das Jahr 2026 (Anpassungsverfahrensaussetzungsgesetz 2026)
* Gesetz zur Reform der Notfallversorgung

In [18]:
json.dump({day: [gesetz['id'] for gesetz in value] for day, value in top.items()}, open('tagesordnung.json', 'wt'))

In [19]:
pre_process(stem('Erste Beratung des von der CDU/CSU-Fraktion eingebrachten Gesetzentwurfs zur rechtssicheren Einführung '))

'gesetz rechtssich einführung'

In [20]:
pre_process(stem(' – Zweite und dritte Beratung des von der Bundesregierung eingebrachten Entwurfs eines Gesetzes zur Durchführung'))

'gesetz durchführung'

In [21]:
pre_process(stem('a) Zweite und dritte Beratung des von der Bundesregierung eingebrachten Entwurfs eines Zweiten Gesetzes zur Änderung des Umweltstatistikgesetzes  '))

'zweit gesetz änderung umweltstatistikgesetz'